### ISSUE TITLE
Broken links at README

### ISSUE THREAD

**Issue by vrescobar** [OnsenUI/awesome-onsenui#2]
None of the links at the readme work https://tutorial.onsen.io/ seem to be offline or missconfigured.

**Comment by masahirotanaka** [comment]
@vrescobar Thanks for the report. We just started investigating.

**Comment by masahirotanaka** [comment]
Please use the following URL: http://tutorial.onsen.io/ 
Looks like the problem was due to AWS environment. I think the problem is solved now.

**Comment by emccorson** [comment]
@masahirotanaka 
It looks like the links still aren't redirecting to onsen.io/playground properly if prefixed with https://

For example tutorial.onsen.io will redirect properly but https://tutorial.onsen.io will not redirect properly.

I will change the README links to point to onsen.io/playground since that is the new URL anyway.

**Comment by emccorson** [comment]
Fixed in 3e49df1d34380d5247b091d0a5b5a6565b17b534
